apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: olmt-radix-example-demo-1
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: frontend
      src: ./frontend
      ports:
       - name: http
         port: 3000
      publicPort: http
    - name: backend
      src: ./backend
      ports:
        - name: http
          port: 6000

  dnsAppAlias:
    environment: prod
    component: frontend
